// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pojo.proto

package com.hxszd.background.netty.protobuf.proto.pojo;

public final class ProtoBufPOJO {
  private ProtoBufPOJO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface summaryMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:summaryMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.summaryMessage.DataType dataType = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <code>.summaryMessage.DataType dataType = 1;</code>
     */
    summaryMessage.DataType getDataType();

    /**
     * <code>.ObjectA objectA = 2;</code>
     */
    boolean hasObjectA();
    /**
     * <code>.ObjectA objectA = 2;</code>
     */
    ObjectA getObjectA();
    /**
     * <code>.ObjectA objectA = 2;</code>
     */
    ObjectAOrBuilder getObjectAOrBuilder();

    /**
     * <code>.ObjectB objectB = 3;</code>
     */
    boolean hasObjectB();
    /**
     * <code>.ObjectB objectB = 3;</code>
     */
    ObjectB getObjectB();
    /**
     * <code>.ObjectB objectB = 3;</code>
     */
    ObjectBOrBuilder getObjectBOrBuilder();

    public summaryMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code summaryMessage}
   */
  public  static final class summaryMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:summaryMessage)
      summaryMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use summaryMessage.newBuilder() to construct.
    private summaryMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private summaryMessage() {
      dataType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private summaryMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              ObjectA.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((ObjectA) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(ObjectA.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ObjectA) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              ObjectB.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((ObjectB) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(ObjectB.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ObjectB) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBufPOJO.internal_static_summaryMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBufPOJO.internal_static_summaryMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              summaryMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code summaryMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ObjectA = 0;</code>
       */
      ObjectA(0),
      /**
       * <code>ObjectB = 1;</code>
       */
      ObjectB(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ObjectA = 0;</code>
       */
      public static final int ObjectA_VALUE = 0;
      /**
       * <code>ObjectB = 1;</code>
       */
      public static final int ObjectB_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return ObjectA;
          case 1: return ObjectB;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return summaryMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:summaryMessage.DataType)
    }

    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      OBJECTA(2),
      OBJECTB(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return OBJECTA;
          case 3: return OBJECTB;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>.summaryMessage.DataType dataType = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.summaryMessage.DataType dataType = 1;</code>
     */
    public DataType getDataType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int OBJECTA_FIELD_NUMBER = 2;
    /**
     * <code>.ObjectA objectA = 2;</code>
     */
    public boolean hasObjectA() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.ObjectA objectA = 2;</code>
     */
    public ObjectA getObjectA() {
      if (dataBodyCase_ == 2) {
         return (ObjectA) dataBody_;
      }
      return ObjectA.getDefaultInstance();
    }
    /**
     * <code>.ObjectA objectA = 2;</code>
     */
    public ObjectAOrBuilder getObjectAOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (ObjectA) dataBody_;
      }
      return ObjectA.getDefaultInstance();
    }

    public static final int OBJECTB_FIELD_NUMBER = 3;
    /**
     * <code>.ObjectB objectB = 3;</code>
     */
    public boolean hasObjectB() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.ObjectB objectB = 3;</code>
     */
    public ObjectB getObjectB() {
      if (dataBodyCase_ == 3) {
         return (ObjectB) dataBody_;
      }
      return ObjectB.getDefaultInstance();
    }
    /**
     * <code>.ObjectB objectB = 3;</code>
     */
    public ObjectBOrBuilder getObjectBOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (ObjectB) dataBody_;
      }
      return ObjectB.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != DataType.ObjectA.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (ObjectA) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (ObjectB) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != DataType.ObjectA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ObjectA) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (ObjectB) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof summaryMessage)) {
        return super.equals(obj);
      }
      summaryMessage other = (summaryMessage) obj;

      boolean result = true;
      result = result && dataType_ == other.dataType_;
      result = result && getDataBodyCase().equals(
          other.getDataBodyCase());
      if (!result) return false;
      switch (dataBodyCase_) {
        case 2:
          result = result && getObjectA()
              .equals(other.getObjectA());
          break;
        case 3:
          result = result && getObjectB()
              .equals(other.getObjectB());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + OBJECTA_FIELD_NUMBER;
          hash = (53 * hash) + getObjectA().hashCode();
          break;
        case 3:
          hash = (37 * hash) + OBJECTB_FIELD_NUMBER;
          hash = (53 * hash) + getObjectB().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static summaryMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static summaryMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static summaryMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static summaryMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static summaryMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static summaryMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static summaryMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static summaryMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static summaryMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static summaryMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static summaryMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static summaryMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(summaryMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code summaryMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:summaryMessage)
        summaryMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufPOJO.internal_static_summaryMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufPOJO.internal_static_summaryMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                summaryMessage.class, Builder.class);
      }

      // Construct using com.hxszd.background.netty.websocket.proto.pojo.protoBufPOJO.summaryMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBufPOJO.internal_static_summaryMessage_descriptor;
      }

      @Override
      public summaryMessage getDefaultInstanceForType() {
        return summaryMessage.getDefaultInstance();
      }

      @Override
      public summaryMessage build() {
        summaryMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public summaryMessage buildPartial() {
        summaryMessage result = new summaryMessage(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (objectABuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = objectABuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (objectBBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = objectBBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof summaryMessage) {
          return mergeFrom((summaryMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(summaryMessage other) {
        if (other == summaryMessage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case OBJECTA: {
            mergeObjectA(other.getObjectA());
            break;
          }
          case OBJECTB: {
            mergeObjectB(other.getObjectB());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        summaryMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (summaryMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <code>.summaryMessage.DataType dataType = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.summaryMessage.DataType dataType = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.summaryMessage.DataType dataType = 1;</code>
       */
      public DataType getDataType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.summaryMessage.DataType dataType = 1;</code>
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.summaryMessage.DataType dataType = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ObjectA, ObjectA.Builder, ObjectAOrBuilder> objectABuilder_;
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public boolean hasObjectA() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public ObjectA getObjectA() {
        if (objectABuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (ObjectA) dataBody_;
          }
          return ObjectA.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return objectABuilder_.getMessage();
          }
          return ObjectA.getDefaultInstance();
        }
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public Builder setObjectA(ObjectA value) {
        if (objectABuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          objectABuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public Builder setObjectA(
          ObjectA.Builder builderForValue) {
        if (objectABuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          objectABuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public Builder mergeObjectA(ObjectA value) {
        if (objectABuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != ObjectA.getDefaultInstance()) {
            dataBody_ = ObjectA.newBuilder((ObjectA) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            objectABuilder_.mergeFrom(value);
          }
          objectABuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public Builder clearObjectA() {
        if (objectABuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          objectABuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public ObjectA.Builder getObjectABuilder() {
        return getObjectAFieldBuilder().getBuilder();
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      public ObjectAOrBuilder getObjectAOrBuilder() {
        if ((dataBodyCase_ == 2) && (objectABuilder_ != null)) {
          return objectABuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (ObjectA) dataBody_;
          }
          return ObjectA.getDefaultInstance();
        }
      }
      /**
       * <code>.ObjectA objectA = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ObjectA, ObjectA.Builder, ObjectAOrBuilder>
          getObjectAFieldBuilder() {
        if (objectABuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = ObjectA.getDefaultInstance();
          }
          objectABuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ObjectA, ObjectA.Builder, ObjectAOrBuilder>(
                  (ObjectA) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return objectABuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ObjectB, ObjectB.Builder, ObjectBOrBuilder> objectBBuilder_;
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public boolean hasObjectB() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public ObjectB getObjectB() {
        if (objectBBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (ObjectB) dataBody_;
          }
          return ObjectB.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return objectBBuilder_.getMessage();
          }
          return ObjectB.getDefaultInstance();
        }
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public Builder setObjectB(ObjectB value) {
        if (objectBBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          objectBBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public Builder setObjectB(
          ObjectB.Builder builderForValue) {
        if (objectBBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          objectBBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public Builder mergeObjectB(ObjectB value) {
        if (objectBBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != ObjectB.getDefaultInstance()) {
            dataBody_ = ObjectB.newBuilder((ObjectB) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            objectBBuilder_.mergeFrom(value);
          }
          objectBBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public Builder clearObjectB() {
        if (objectBBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          objectBBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public ObjectB.Builder getObjectBBuilder() {
        return getObjectBFieldBuilder().getBuilder();
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      public ObjectBOrBuilder getObjectBOrBuilder() {
        if ((dataBodyCase_ == 3) && (objectBBuilder_ != null)) {
          return objectBBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (ObjectB) dataBody_;
          }
          return ObjectB.getDefaultInstance();
        }
      }
      /**
       * <code>.ObjectB objectB = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ObjectB, ObjectB.Builder, ObjectBOrBuilder>
          getObjectBFieldBuilder() {
        if (objectBBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = ObjectB.getDefaultInstance();
          }
          objectBBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ObjectB, ObjectB.Builder, ObjectBOrBuilder>(
                  (ObjectB) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return objectBBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:summaryMessage)
    }

    // @@protoc_insertion_point(class_scope:summaryMessage)
    private static final summaryMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new summaryMessage();
    }

    public static summaryMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<summaryMessage>
        PARSER = new com.google.protobuf.AbstractParser<summaryMessage>() {
      @Override
      public summaryMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new summaryMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<summaryMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<summaryMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public summaryMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ObjectAOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ObjectA)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userId = 4;</code>
     */
    int getUserId();

    /**
     * <code>string userName = 5;</code>
     */
    String getUserName();
    /**
     * <code>string userName = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();
  }
  /**
   * Protobuf type {@code ObjectA}
   */
  public  static final class ObjectA extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ObjectA)
      ObjectAOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ObjectA.newBuilder() to construct.
    private ObjectA(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectA() {
      userId_ = 0;
      userName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectA(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 32: {

              userId_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBufPOJO.internal_static_ObjectA_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBufPOJO.internal_static_ObjectA_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ObjectA.class, Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private int userId_;
    /**
     * <code>int32 userId = 4;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 5;
    private volatile Object userName_;
    /**
     * <code>string userName = 5;</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(4, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ObjectA)) {
        return super.equals(obj);
      }
      ObjectA other = (ObjectA) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ObjectA parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ObjectA parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ObjectA parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ObjectA parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ObjectA parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ObjectA parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ObjectA parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ObjectA parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ObjectA parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ObjectA parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ObjectA parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ObjectA parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ObjectA prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ObjectA}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ObjectA)
        ObjectAOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufPOJO.internal_static_ObjectA_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufPOJO.internal_static_ObjectA_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ObjectA.class, Builder.class);
      }

      // Construct using com.hxszd.background.netty.websocket.proto.pojo.protoBufPOJO.ObjectA.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        userName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBufPOJO.internal_static_ObjectA_descriptor;
      }

      @Override
      public ObjectA getDefaultInstanceForType() {
        return ObjectA.getDefaultInstance();
      }

      @Override
      public ObjectA build() {
        ObjectA result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ObjectA buildPartial() {
        ObjectA result = new ObjectA(this);
        result.userId_ = userId_;
        result.userName_ = userName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ObjectA) {
          return mergeFrom((ObjectA)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ObjectA other) {
        if (other == ObjectA.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ObjectA parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ObjectA) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 4;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 4;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 4;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private Object userName_ = "";
      /**
       * <code>string userName = 5;</code>
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string userName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 5;</code>
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 5;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 5;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ObjectA)
    }

    // @@protoc_insertion_point(class_scope:ObjectA)
    private static final ObjectA DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ObjectA();
    }

    public static ObjectA getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectA>
        PARSER = new com.google.protobuf.AbstractParser<ObjectA>() {
      @Override
      public ObjectA parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectA(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObjectA> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ObjectA> getParserForType() {
      return PARSER;
    }

    @Override
    public ObjectA getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ObjectBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ObjectB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userId = 6;</code>
     */
    int getUserId();

    /**
     * <code>string phoneNum = 7;</code>
     */
    String getPhoneNum();
    /**
     * <code>string phoneNum = 7;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumBytes();
  }
  /**
   * Protobuf type {@code ObjectB}
   */
  public  static final class ObjectB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ObjectB)
      ObjectBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ObjectB.newBuilder() to construct.
    private ObjectB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectB() {
      userId_ = 0;
      phoneNum_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 48: {

              userId_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              phoneNum_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBufPOJO.internal_static_ObjectB_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBufPOJO.internal_static_ObjectB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ObjectB.class, Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 6;
    private int userId_;
    /**
     * <code>int32 userId = 6;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int PHONENUM_FIELD_NUMBER = 7;
    private volatile Object phoneNum_;
    /**
     * <code>string phoneNum = 7;</code>
     */
    public String getPhoneNum() {
      Object ref = phoneNum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        phoneNum_ = s;
        return s;
      }
    }
    /**
     * <code>string phoneNum = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumBytes() {
      Object ref = phoneNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phoneNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(6, userId_);
      }
      if (!getPhoneNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phoneNum_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, userId_);
      }
      if (!getPhoneNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, phoneNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ObjectB)) {
        return super.equals(obj);
      }
      ObjectB other = (ObjectB) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getPhoneNum()
          .equals(other.getPhoneNum());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + PHONENUM_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNum().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ObjectB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ObjectB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ObjectB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ObjectB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ObjectB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ObjectB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ObjectB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ObjectB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ObjectB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ObjectB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ObjectB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ObjectB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ObjectB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ObjectB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ObjectB)
        ObjectBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufPOJO.internal_static_ObjectB_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufPOJO.internal_static_ObjectB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ObjectB.class, Builder.class);
      }

      // Construct using com.hxszd.background.netty.websocket.proto.pojo.protoBufPOJO.ObjectB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        phoneNum_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBufPOJO.internal_static_ObjectB_descriptor;
      }

      @Override
      public ObjectB getDefaultInstanceForType() {
        return ObjectB.getDefaultInstance();
      }

      @Override
      public ObjectB build() {
        ObjectB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ObjectB buildPartial() {
        ObjectB result = new ObjectB(this);
        result.userId_ = userId_;
        result.phoneNum_ = phoneNum_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ObjectB) {
          return mergeFrom((ObjectB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ObjectB other) {
        if (other == ObjectB.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getPhoneNum().isEmpty()) {
          phoneNum_ = other.phoneNum_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ObjectB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ObjectB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 6;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 6;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 6;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private Object phoneNum_ = "";
      /**
       * <code>string phoneNum = 7;</code>
       */
      public String getPhoneNum() {
        Object ref = phoneNum_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          phoneNum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string phoneNum = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumBytes() {
        Object ref = phoneNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phoneNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phoneNum = 7;</code>
       */
      public Builder setPhoneNum(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNum = 7;</code>
       */
      public Builder clearPhoneNum() {
        
        phoneNum_ = getDefaultInstance().getPhoneNum();
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNum = 7;</code>
       */
      public Builder setPhoneNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNum_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ObjectB)
    }

    // @@protoc_insertion_point(class_scope:ObjectB)
    private static final ObjectB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ObjectB();
    }

    public static ObjectB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectB>
        PARSER = new com.google.protobuf.AbstractParser<ObjectB>() {
      @Override
      public ObjectB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObjectB> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ObjectB> getParserForType() {
      return PARSER;
    }

    @Override
    public ObjectB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_summaryMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_summaryMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectA_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ObjectA_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ObjectB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\npojo.proto\"\250\001\n\016summaryMessage\022*\n\010dataT" +
      "ype\030\001 \001(\0162\030.summaryMessage.DataType\022\033\n\007o" +
      "bjectA\030\002 \001(\0132\010.ObjectAH\000\022\033\n\007objectB\030\003 \001(" +
      "\0132\010.ObjectBH\000\"$\n\010DataType\022\013\n\007ObjectA\020\000\022\013" +
      "\n\007ObjectB\020\001B\n\n\010dataBody\"+\n\007ObjectA\022\016\n\006us" +
      "erId\030\004 \001(\005\022\020\n\010userName\030\005 \001(\t\"+\n\007ObjectB\022" +
      "\016\n\006userId\030\006 \001(\005\022\020\n\010phoneNum\030\007 \001(\tBA\n/com" +
      ".hxszd.background.netty.websocket.proto." +
      "pojoB\014protoBufPOJOH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_summaryMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_summaryMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_summaryMessage_descriptor,
        new String[] { "DataType", "ObjectA", "ObjectB", "DataBody", });
    internal_static_ObjectA_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ObjectA_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ObjectA_descriptor,
        new String[] { "UserId", "UserName", });
    internal_static_ObjectB_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ObjectB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ObjectB_descriptor,
        new String[] { "UserId", "PhoneNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
